name: emartconsumer
description: Application for eMart user.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.2+2

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  # firebase
  firebase_auth: ^4.19.0
  cloud_firestore: ^5.4.3
  google_sign_in: ^6.2.1
  firebase_app_check: ^0.3.1+3
  firebase_database: ^11.1.4
  firebase_storage: ^12.3.2
  sign_in_with_apple: ^6.1.2
  crypto: ^3.0.5
  geocoding: ^3.0.0
  flutter_local_notifications: ^17.2.3
  googleapis_auth: ^1.6.0

  cached_network_image: ^3.4.1
  flutter_svg: ^2.0.10+1
  shared_preferences: ^2.3.2
  intl_phone_number_input: ^0.7.4
  url_launcher: ^6.3.0
  uuid: ^4.5.1
  google_fonts: ^6.2.1
  get: ^4.6.6
  pin_code_fields: ^8.0.1
  intl: ^0.19.0
  flutter_easyloading: ^3.0.5
  country_code_picker: ^3.0.0
  google_maps_flutter: ^2.9.0
  flutter_polyline_points: ^2.1.0
  flutter_rating_bar: ^4.0.1
  bottom_picker: ^2.8.0
  flutter_staggered_grid_view: ^0.7.0
  flutter_widget_from_html: ^0.15.2
  mobile_scanner: ^5.2.3

  flutter_dash: ^1.0.0
  provider: ^6.1.2
  dotted_border: ^2.1.0
  clipboard: ^0.1.3
  image_picker: ^1.1.2
  video_thumbnail: ^0.5.3
  path_provider: ^2.1.4
  photo_view: ^0.15.0
  video_player: ^2.9.1
  flutter_email_sender: ^6.0.3
  flutter_html: any
  share_plus: ^10.0.2
  map_launcher: ^3.5.0
  google_maps_place_picker_mb: ^3.1.2
  easy_localization: ^3.0.7
  date_picker_plus: ^4.1.0
  location: ^6.0.2
  mailer: ^6.2.0
  moor_flutter: ^4.1.0
  font_awesome_flutter: ^10.7.0
  syncfusion_flutter_datepicker: ^27.1.50


  esc_pos_utils: ^1.1.0
  print_bluetooth_thermal: ^1.1.1
  lottie: ^3.1.2
  video_compress: ^3.1.3

  osm_nominatim: ^3.0.1
  flutter_osm_plugin: ^1.3.3+1

  #payment dependency
  flutter_stripe: ^11.1.0
  razorpay_flutter: ^1.3.7
  flutter_paypal_native: ^2.1.0

  firebase_messaging: any

dependency_overrides:
  webview_flutter: ^4.9.0
  firebase_messaging: ^15.1.3
  firebase_core: ^2.28.0
  http: ^1.2.2
  js: ^0.7.1


dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/translations/
    - assets/icons/
    - assets/json/
    - assets/fonts/
    - assets/

  fonts:
    - family: RadioCanadaBig-Bold
      fonts:
        - asset: assets/fonts/RadioCanadaBig-Bold.ttf

    - family: Metropolis-Medium
      fonts:
        - asset: assets/fonts/RadioCanadaBig-Medium.ttf

    - family: RadioCanadaBig-Regular
      fonts:
        - asset: assets/fonts/RadioCanadaBig-Regular.ttf

    - family: RadioCanadaBig-SemiBold
      fonts:
        - asset: assets/fonts/RadioCanadaBig-SemiBold.ttf

